---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: debian-7.11
  - name: debian-8.5
  - name: centos-6.8
  - name: centos-7.2
  - name: freebsd-9.3
  - name: freebsd-10.3
  - name: fedora-21
  - name: fedora-22
  - name: fedora-23
  - name: fedora-24

suites:
  - name: default
    run_list:
      - recipe[hostname::default]
    attributes:
      set_fqdn: test.example.com
  - name: wildcard
    run_list:
      - recipe[hostname::default]
    provisioner:
      solo_rb:
        node_name: test
    attributes:
      set_fqdn: '*.example.com'
