AllCops:
  DisplayCopNames: true
  Exclude:
    - tmp/**

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Exclude:
    - Thorfile
